# Generated by Django 3.2.16 on 2022-12-21 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задача', 'verbose_name_plural': 'задачи'},
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(help_text='Создатель задачи.', on_delete=django.db.models.deletion.CASCADE, related_name='creator_board', to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
                ('executors', models.ManyToManyField(help_text='Участтники доски.', to=settings.AUTH_USER_MODEL, verbose_name='исполнители')),
                ('tasks', models.ManyToManyField(help_text='Задачи определенной доски.', to='board.Task', verbose_name='задачи')),
            ],
        ),
    ]
