# Generated by Django 3.2.16 on 2022-12-22 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20221221_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'доска', 'verbose_name_plural': 'доски'},
        ),
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 12, 22, 20, 12, 38, 284095), help_text='Название доски.', max_length=30, verbose_name='название'),
            preserve_default=False,
        ),
    ]
