# Generated by Django 3.2.16 on 2022-12-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_task_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Дата дедлайна.', null=True, verbose_name='конец'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Дата начала выполнения задачи.', null=True, verbose_name='начало'),
        ),
    ]
