# Generated by Django 3.2.16 on 2022-12-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_board_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks',
        ),
    ]
