# Generated by Django 3.2.16 on 2022-12-22 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0006_auto_20221222_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='executors',
            field=models.ManyToManyField(help_text='Участники доски.', to=settings.AUTH_USER_MODEL, verbose_name='исполнители'),
        ),
    ]
