# Generated by Django 3.2.16 on 2022-12-22 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0008_merge_20221222_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='creator',
            field=models.ForeignKey(default=1, help_text='Создатель доски.', on_delete=django.db.models.deletion.CASCADE, related_name='creator_board', to='users.customuser', verbose_name='создатель'),
            preserve_default=False,
        ),
    ]
