# Generated by Django 3.2.16 on 2022-12-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_board_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tasks',
            field=models.ManyToManyField(help_text='Задачи определенной доски.', to='board.Task', verbose_name='задачи'),
        ),
    ]
